### ISSUE TITLE
Question 8 Lesson two...

### ISSUE THREAD

**Issue by mahagadorn** [pearselab/r-intro-mahagadorn#12]
Hello Will,

I know we already discussed the asymptote aspect of the Gompertz function problem, however, I am trying to add the additional color (purple) to the plot and I was hoping you could tell me if the way I did it is appropriate.  I tried to implement you "hint" but I don't think I understand how the numbers correlate to our numbers and colors.  I did it this way, 

```

plotPSMultipleCol.fun <- function(a,b,c,t){
  colors <- rep("black", length(TimeRec))  
  pop.growth <- TimeRec
  for(i in 1:length(TimeRec)){
    pop.growth <- popsize.fun(a,b,c,t,..) 
    if(pop.growth[i] > b){
      colors[i] <- "red"
    }
    if(pop.growth[i] > a & b){
      colors[i] <- "purple"
    }
  }
  plot(TimeRec, pop.growth,
       xlab = "Time Recordings (in years)", 
       ylab = "Population Size (in millions)", 
       main = "Gompertz Curve: Population Size Changes Over Time",
       col= colors)
} 

Mult.col.PS.plot<- plotPSMultipleCol.fun(a=500, b=95, c=0.10, t=TimeRec)

```

Even though I couldn't get you hint to work, is this way still appropriate?  When I changed the " if(pop.growth[i] > a & b){ " to  " if(pop.growth[i] > c & b){ " , the purple showed up just fine.  Is this an acceptable way to accomplish question #8.  Thank you.

Mallory

**Comment by willpearse** [comment]
Ah - I'm afraid this isn't quite what I would like, because you're not quite using `&` in the correct sense. It needs two valid expressions either side of it. So, for example, `if(x > 1 & y > 1)` is valid, but `if(x & y > 1)` isn't. Does that make sense? In English, it's the equivalent of saying "If x is greater than one AND y is greater than one" being OK, but R doesn't understanding "if x AND y are greater than one". Make sense?

**Comment by mahagadorn** [comment]
That makes perfect sense!

```

  for(i in 1:length(TimeRec)){
    pop.growth <- popsize.fun(a,b,c,t,..) 
    if(pop.growth[i] > b){
      colors[i] <- "red"
    }
    if(pop.growth[i] > a & pop.growth[i] > b){
      colors[i] <- "purple"
    }
  }

```

So what I just attached is more appropriate (and hopefully still the correct answer).   Is it weird that I wasn't given an error message? Or did R just "ignore" that part of my function?

**Comment by willpearse** [comment]
You're putting `...` in your function calls, which you shouldn't do (if you don't know what it's doing, don't do it :D) but otherwise looks great! Nice work!

As for why it worked... I imagine it's due to lazy evaluation. R won't evaluate the right-hand side of an `&` unless the left-hand side is found to be `TRUE` (by definition it can never be `TRUE` if either is `FALSE`, so there's no need and it saves time). This behaviour can be bypassed with `&&`, I think. Anyway, because R never evaluates the expression, it never checks it for correctness (that's lazy evaluation) and so the error is never thrown. The technical term is that the "promise is not evaluated", and so if you ever get an error message saying "promise broken" you know what has happened!...

**Comment by mahagadorn** [comment]
Oh okay great! That's a great explanation of lazy evaluation.  Thank you.

Also, sorry about the `...` , I have it in my list of things to go back and revise (along with return vs print).

**Comment by willpearse** [comment]
The only thing you need to apologise about is constantly apologising!... :D

No worries. It never sinks in first time: practice makes perfect!
